/**
 * Calendar attachments (RFC 5545), generated by hand.
 *
 * No `ics` package for the same reason there's no `googleapis`: this is one
 * well-specified text format and the library would be more code than the spec.
 *
 * METHOD is PUBLISH, not REQUEST, and that's deliberate. Google already emails
 * the prospect a real invite (createCalendarEvent uses sendUpdates=all). A
 * second REQUEST from us would land as a competing invitation for the same
 * event and some clients show it as a conflicting duplicate. PUBLISH is a plain
 * "add this to your calendar" file — useful to anyone not on Gmail, harmless to
 * everyone else.
 */

const CRLF = "\r\n";

/** Backslash, semicolon, comma and newline are the four that must be escaped. */
function escapeText(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\r?\n/g, "\\n");
}

/**
 * Lines cap at 75 *octets* — not characters. Continuations begin with one
 * space, which itself counts toward the 75, hence the 74 on later chunks.
 * Splitting mid-character would corrupt any non-ASCII text (a name with an
 * accent, an emoji in the notes), so back off to a UTF-8 lead byte.
 */
function fold(line: string): string {
  const bytes = Buffer.from(line, "utf8");
  if (bytes.length <= 75) return line;

  const chunks: string[] = [];
  let start = 0;
  let limit = 75;

  while (start < bytes.length) {
    let end = Math.min(start + limit, bytes.length);
    // 0b10xxxxxx is a continuation byte; walk back to the character boundary.
    while (end < bytes.length && (bytes[end] & 0xc0) === 0x80) end -= 1;
    chunks.push(bytes.subarray(start, end).toString("utf8"));
    start = end;
    limit = 74;
  }

  return chunks.join(`${CRLF} `);
}

/** 2026-07-29T13:00:00.000Z -> 20260729T130000Z */
export function toIcsUtc(iso: string | Date): string {
  const date = typeof iso === "string" ? new Date(iso) : iso;
  if (Number.isNaN(date.getTime())) throw new Error(`Invalid date for ics: ${String(iso)}`);
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
}

export type IcsInput = {
  /** Stable across re-sends for the same booking, so clients update instead of duplicating. */
  uid: string;
  summary: string;
  description?: string;
  location?: string;
  startsAt: string;
  endsAt: string;
  organizerName: string;
  organizerEmail: string;
  url?: string;
};

export function buildIcs(input: IcsInput): string {
  const lines = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//CMB Bookings//Booking//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "BEGIN:VEVENT",
    `UID:${input.uid}`,
    `DTSTAMP:${toIcsUtc(new Date())}`,
    `DTSTART:${toIcsUtc(input.startsAt)}`,
    `DTEND:${toIcsUtc(input.endsAt)}`,
    `SUMMARY:${escapeText(input.summary)}`,
    input.description ? `DESCRIPTION:${escapeText(input.description)}` : null,
    input.location ? `LOCATION:${escapeText(input.location)}` : null,
    input.url ? `URL:${escapeText(input.url)}` : null,
    `ORGANIZER;CN=${escapeText(input.organizerName)}:mailto:${input.organizerEmail}`,
    "STATUS:CONFIRMED",
    "SEQUENCE:0",
    "TRANSP:OPAQUE",
    "BEGIN:VALARM",
    "TRIGGER:-PT2H",
    "ACTION:DISPLAY",
    `DESCRIPTION:${escapeText(input.summary)}`,
    "END:VALARM",
    "END:VEVENT",
    "END:VCALENDAR",
  ].filter((line): line is string => line !== null);

  // Trailing CRLF matters: some parsers drop an unterminated final line.
  return lines.map(fold).join(CRLF) + CRLF;
}
